baseURL = 'https://lucasbemo.github.io/'
title = "Lucas Zamboni Blog"
theme = "hugo-theme-cleanwhite"
languageCode = "en-us"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
googleAnalytics = ""
preserveTaxonomyNames = true
paginate = 5 #frontpage pagination
hasCJKLanguage = true


[outputs]
home = ["HTML", "RSS", "Algolia"]

[params]
  custom_css = ["css/lucasbemo.css"]

  header_image = "img/road-166543_1920.jpeg"
  SEOTitle = "Lucas Zamboni Blog"
  description = "Lucas Zamboni"
  keyword = "Lucas Zamboni, Lucas Bemo Blog, PaaS, Istio, Kubernetes, Microservice"
  slogan = "Walk on! What you got, they can't steal it."

  image_404 = "img/404-bg.jpg"
  title_404 = "Not Found :("

  # leancloud storage for page view counter
  page_view_conter = true 
  leancloud_app_id = ""
  leancloud_app_key = ""

  # algolia site search
  algolia_search = true
  algolia_appId = ""
  algolia_indexName = ""
  algolia_apiKey = ""

  # Sidebar settings
  # sidebar_about_description = "Software Engineer, Open Source Enthusiast and Life Adventurer"
  sidebar_about_description = "Software Engineer/Architecture"
  #sidebar_avatar = "img/avatar-zhaohuabing.jpg"      # use absolute URL, seeing it's used in both `/` and `/about/`
  # sidebar_avatar = "img/zhaohuabing.png"      # use absolute URL, seeing it's used in both `/` and `/about/`
  sidebar_avatar = "img/eu_beco_do_batman-cropped.png"

  featured_tags = true 
  featured_condition_size = 1 

  # Baidu Analytics
  ba_track_id = ""
  
  # We need a proxy to access Disqus api in China
  # Follow https://github.com/zhaohuabing/disqus-php-api to set up your own disqus proxy
  disqus_proxy = ""
  disqus_site = ""

  #Enable wechat pay & alipay to allow readers send reward money if they like the articles 
  reward = true 
  # reward_guide = "如果这篇文章对你有用,请随意打赏" 

  friends = false
  bookmarks = false
  about_me = true

  [params.social]
  rss            = true 
  email          = "lucasbemo@gmail.com"
  twitter       = "https://twitter.com/lucasbemo"
  linkedin       = "https://www.linkedin.com/in/lucasbemo"
  github         = "https://github.com/lucasbemo"
  #facebook      = "full profile url in facebook"
  #googleplus    = "full profile url in googleplus"
  # stackoverflow  = "https://stackoverflow.com/users/lucasbemo"
  #instagram     = "full profile url in instagram"
  # wechat         = "your wechat qr code image"
#  medium         = "full profile url in medium"
  #pinterest     = "full profile url in pinterest"

  
  
  [[params.friend_link]]
  title = "Linda的博客"
  href =  "https://zhaozhihan.com"

  [[params.bookmark_link]]
  title =  "Martin Fowler"
  href =  "https://martinfowler.com"
  [[params.bookmark_link]]
  title = "ServiceMesher"
  href =  "http://www.servicemesher.com"
  [[params.bookmark_link]]
  title =  "Pxhere"
  href = "https://pxhere.com"
  [[params.bookmark_link]]
  title = "unsplash"
  href = "https://unsplash.com"
  
  # [[params.addtional_menus]]
  # title =  "BOOKS"
  # href =  "/top/books/"
  [[params.addtional_menus]]
  title =  "ABOUT"
  href =  "/top/about/"

[outputFormats.Algolia]
baseName = "algolia"
isPlainText = true
mediaType = "application/json"
notAlternative = true

[params.algolia]
vars = ["title", "summary", "date", "publishdate", "expirydate", "permalink"]
params = ["categories", "tags"] 